imports:
    - 'package-container.yml'
    - 'vendor/opine/cache/config/package-container.yml'
    - 'vendor/opine/config/config/package-container.yml'
    - 'vendor/opine/container/config/package-container.yml'
    - 'vendor/opine/pubsub/config/package-container.yml'