imports:
    - package-container.yml
    - ../../vendor/opine/cache/config/containers/package-container.yml
    - ../../vendor/opine/config/config/containers/package-container.yml
    - ../../vendor/opine/container/config/containers/package-container.yml
    - ../../vendor/opine/pubsub/config/containers/package-container.yml
